CREATE TABLE CLIENT(
	ID		UNIQUEIDENTIFIER	NOT NULL,
	[NAME]	VARCHAR(100)		NOT NULL,
	CPF		VARCHAR(11)			NOT NULL,
	PRIMARY KEY(ID)
);
GO

CREATE TABLE ADDRESS(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	[PUBLICAREA]	VARCHAR(100)		NOT NULL,
	COMPLEMENT		VARCHAR(50)			NOT NULL,
	NUMBER			VARCHAR(10)			NOT NULL,
	NEIGHBORHOOD	VARCHAR(50)			NOT NULL,
	CITY			VARCHAR(100)		NOT NULL,
	[STATE]			VARCHAR(2)			NOT NULL,
	CEP				VARCHAR(10)			NOT NULL,
	CLIENT_ID		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID)
);
GO

CREATE PROCEDURE SP_INSERIR_CLIENTE
	@NAME			VARCHAR(100),
	@CPF			VARCHAR(11),
	@PUBLICAREA		VARCHAR(100),
	@COMPLEMENT		VARCHAR(50),
	@NUMBER			VARCHAR(10),
	@NEIGHBORHOOD	VARCHAR(50),
	@CITY			VARCHAR(50),
	@STATE			VARCHAR(2),
	@CEP			VARCHAR(10)
AS 
DECLARE
	@CLIENT_ID	UNIQUEIDENTIFIER,
	@ADDRESS_ID	UNIQUEIDENTIFIER
BEGIN
	SET @CLIENT_ID = NEWID();
	SET	@ADDRESS_ID = NEWID();

	BEGIN TRANSACTION;

	INSERT INTO CLIENT(ID,[NAME],CPF) 
	VALUES(@CLIENT_ID, @NAME,@CPF);


	INSERT INTO ADDRESS(ID,PUBLICAREA,COMPLEMENT, NUMBER,NEIGHBORHOOD, CITY, [STATE], CEP, CLIENT_ID)
	VALUES(@ADDRESS_ID, @PUBLICAREA, @COMPLEMENT, @NUMBER, @NEIGHBORHOOD, @CITY, @STATE, @CEP,@CLIENT_ID);

	COMMIT;
END;
GO